fix function prototypes
GCC 14 has switched "incompatible pointer type: warnigs into errors. In
our case it's about missing "const", fix them.

for example
../src/files.c:330:48: error: passing argument 1 of ‘write_buffer_with_func’ from incompatible pointer type [-Wincompatible-pointer-types]
  330 |                         write_buffer_with_func(write_file);
      |                                                ^~~~~~~~~~
      |                                                |
      |                                                void (*)(char *, unsigned int)
In file included from ../src/files.c:37:
../src/buffer.h:33:36: note: expected ‘void (*)(const char *, unsigned int)’ but argument is of type ‘void (*)(char *, unsigned int)’
   33 | void write_buffer_with_func(void (*func)(const char *, unsigned int));
      |                             ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~